catalina: hmc-util: Check ERoT BackgroundCopyStatus before firmware update
Summary:
When a firmware update completes successfully, ERoT performs a background copy of the firmware image. If a new firmware update is initiated while this background copy is still in progress, the update may fail.

This commit adds a check for ERoT BackgroundCopyStatus before starting a firmware update and displays the status at the beginning of the process. Additionally, add extra message to inform user when update fail if ERoT BackgroundCopyStatus was not showing "Completed".

Test Results:
```
root@bmc:~# fw-util hmc --force --update sbios /tmp/F0N_3A03.BIN
HGX_ERoT_CPU_0 BackgroundCopyStatus: InProgress
HGX_ERoT_CPU_1 BackgroundCopyStatus: InProgress
CMD: curl --connect-timeout 3 -s -u root:0penBmc -H 'Expect:' -L -X POST 'http://172.31.13.251/redfish/v1/UpdateService/update-multipart' -F 'UpdateParameters={"Targets":["/redfish/v1/UpdateService/FirmwareInventory/HGX_FW_CPU_0","/redfish/v1/UpdateService/FirmwareInventory/HGX_FW_CPU_1"], "ForceUpdate":true} ;type=application/json' -F UpdateFile=@/tmp/F0N_3A03.BIN
TASK_ID: /redfish/v1/TaskService/Tasks/14

[0] The task with Id '14' has started.
[1] The task with Id '14' has changed to progress 100 percent complete.
[2] The target device 'HGX_FW_CPU_0' will be updated with image 'F0N_3A03'.
[3] The task with Id '14' has completed with errors.
[4] The target device 'HGX_FW_CPU_1' will be updated with image 'F0N_3A03'.
[5] Transfer of image 'F0N_3A03' to 'HGX_FW_CPU_1' failed.
[6] The resource property 'HGX_FW_CPU_1' has detected errors of type 'ERoT is busy'.
[7] Transfer of image 'F0N_3A03' to 'HGX_FW_CPU_0' failed.
[8] The resource property 'HGX_FW_CPU_0' has detected errors of type 'ERoT is busy'.
PercentComplete: 100 ...... (seconds: 0)
Update finished, state: Exception, status: Critical
Firmware update failed might be due to ERoT is busy, please try update again.
Force upgrade of hmc : sbios failed
```

X-link: https://github.com/facebookexternal/openbmc.quanta/pull/4589

Reviewed By: jamesatha

Differential Revision: D70889195

fbshipit-source-id: daa4a1434fc41ba6f2508eec5c6fc3d1a466ef89

diff --git a/meta-facebook/meta-catalina/recipes-catalina/hmc-util/files/hmc-util b/meta-facebook/meta-catalina/recipes-catalina/hmc-util/files/hmc-util
--- a/meta-facebook/meta-catalina/recipes-catalina/hmc-util/files/hmc-util
+++ b/meta-facebook/meta-catalina/recipes-catalina/hmc-util/files/hmc-util
@@ -109,12 +109,71 @@ prepare_update_target_str()
     return 0
 }
 
+is_erot_background_copy_status_done()
+{
+    EROT_URL="${HMC_URL_PREFIX}/redfish/v1/Chassis/$1"
+    CURL_CMD="curl --connect-timeout ${CURL_CONNECT_TIMEOUT} -s '${EROT_URL}'"
+    if ! CURL_DATA=$(eval "${CURL_CMD}"); then
+        echo "NA (hmc no response)"
+        return 1
+    fi
+
+    BC_STATUS="$(echo "${CURL_DATA}" | jq -r '.Oem.Nvidia.BackgroundCopyStatus')"
+    echo "$1 BackgroundCopyStatus: $BC_STATUS"
+
+    if [ "$BC_STATUS" != "Completed" ]; then
+        return 1
+    fi
+    return 0
+}
+
+check_erot_background_copy_status()
+{
+    ALL_EROT_BC_DONE=true
+
+    case "$1" in
+        "all"|"bundle")
+            is_erot_background_copy_status_done "HGX_ERoT_BMC_0" || ALL_EROT_BC_DONE=false
+            is_erot_background_copy_status_done "HGX_ERoT_FPGA_0" || ALL_EROT_BC_DONE=false
+            is_erot_background_copy_status_done "HGX_ERoT_FPGA_1" || ALL_EROT_BC_DONE=false
+            ;;
+        "sbios")
+            is_erot_background_copy_status_done "HGX_ERoT_CPU_0" || ALL_EROT_BC_DONE=false
+            is_erot_background_copy_status_done "HGX_ERoT_CPU_1" || ALL_EROT_BC_DONE=false
+            ;;
+        "HGX_FW_BMC_0")
+            is_erot_background_copy_status_done "HGX_ERoT_BMC_0" || ALL_EROT_BC_DONE=false
+            ;;
+        "HGX_FW_FPGA_0")
+            is_erot_background_copy_status_done "HGX_ERoT_FPGA_0" || ALL_EROT_BC_DONE=false
+            ;;
+        "HGX_FW_FPGA_1")
+            is_erot_background_copy_status_done "HGX_ERoT_FPGA_1" || ALL_EROT_BC_DONE=false
+            ;;
+        "HGX_FW_CPU_0")
+            is_erot_background_copy_status_done "HGX_ERoT_CPU_0" || ALL_EROT_BC_DONE=false
+            ;;
+        "HGX_FW_CPU_1")
+            is_erot_background_copy_status_done "HGX_ERoT_CPU_1" || ALL_EROT_BC_DONE=false
+            ;;
+    esac
+
+    if [ "$ALL_EROT_BC_DONE" = false ]; then
+        return 1
+    fi
+
+    return 0
+}
+
 update_comp()
 {
     if ! TARGET_STR=$(prepare_update_target_str "$1"); then
         echo "failed: Unknow component, $1"
         exit 1
     fi
+
+    EROT_BUSY=false
+    check_erot_background_copy_status "$1" || EROT_BUSY=true
 
     FORCE_UPDATE=""
     if [ "$3" = "--force-update" ]; then
@@ -167,6 +226,9 @@ update_comp()
             if [ "$TASK_STATE" = "Completed" ]; then
                 return 0
             else
+                if [ "$EROT_BUSY" = true ]; then
+                    echo "Firmware update failed might be due to ERoT is busy, please try update again."
+                fi
                 return 1
             fi
         fi
